---

- name: устанавливаем grafana
  apt:
    deb: https://dl.grafana.com/oss/release/grafana_10.0.3_amd64.deb
    state: present

- name: запускаем службу
  systemd:
    name: grafana-server
    enabled: yes
    state: started


- name: Делаем паузу на 1 минуту для загруки Grafana
  ansible.builtin.pause:
    minutes: 1


- name: создаём источник данных prometheus для grafana
  community.grafana.grafana_datasource:
    name: prometheus
    grafana_url: "http://localhost:3000"
    grafana_user: "admin"
    grafana_password: "admin"
    ds_type: prometheus
    ds_url: http://localhost:9090
    tls_skip_verify: true
    is_default: true

- name: Импортируем дашборд в grafana
  community.grafana.grafana_dashboard:
    grafana_url: "http://localhost:3000"
    grafana_user: "admin"
    grafana_password: "admin"
    dashboard_id: 1860
    dashboard_revision: 31


