all:
  vars:
    tower_user_name: master
    site_name: otus.tst
    wordpress_ver: 6.2.2
    ansible_host_key_checking: False
    ansible_ssh_host_key_checking: False
dbservers:      
  hosts:
    sqlmaster:
      ansible_ssh_host: 172.17.50.116
      human_name: sql-master
    sqlslave:
      ansible_ssh_host: 172.17.50.117
      human_name: sql-slave

monservers:
  hosts:
    logmon:
      ansible_ssh_host: 172.17.50.100
      human_name: log-mon
