---

- name: Распаковываем архив с дистрибутивом Wordpress
  unarchive:
    src: "https://ru.wordpress.org/wordpress-{{ wordpress_ver }}-ru_RU.tar.gz"
    dest: /var/www/{{ site_name }}/
    remote_src: yes
    extra_opts: [--strip-components=1]
    creates: /var/www/{{ site_name }}/index.php

# [--strip-components=1] - указывает, количество директорий, которые нужные пропустить в пути при разъархивацию


- name: Скачиваем утилиту wp
  uri:
    url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    dest: /usr/local/bin/wp
    mode: 755

- name: Создаем базу данных для wordpress
  mysql_db:
    name: wordpress
    state: present
    encoding: utf8
    login_unix_socket: /run/mysqld/mysqld.sock

- name: Создаем пользователя для базы wordpress
  mysql_user:
    name: wordpress
    password: wordpass123
    priv: 'wordpress.*:ALL'
    state: present
    login_unix_socket: /run/mysqld/mysqld.sock

- name: Копируем конфигурационный файл для wordpress
  copy:
    src: wp-config.php
    dest: /var/www/{{ site_name }}
    remote_src: no
    mode: 0644
    owner: www-data
    group: www-data

- name: Устанавливаем wordpress
  command: /usr/local/bin/wp core install --url=otus.tst --title="otus tests" --admin_name=admin --admin_email=admin@otus.tst --skip-email --admin_password=password --allow-root --path=/var/www/{{ site_name }}

- name: Настраиваем русский язык
  command: /usr/local/bin/wp language core install ru_RU --allow-root --path=/var/www/{{ site_name }} && /usr/local/bin/wp language core activate ru_RU --allow-root --path=/var/www/{{ site_name }}
